version: "3.9"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/myapp
      - REDIS_HOST=redis
    networks:
      - app-network
    depends_on:
      - mongo
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:7
    restart: always
    volumes:
      - mongo-data:/data/db
    secrets:
      - mongo_root_password
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_password

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - app-network

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - web
      - api
    networks:
      - app-network

volumes:
  mongo-data:
  redis-data:

networks:
  app-network:

secrets:
  mongo_root_password:
    file: ./secrets/mongo_root_password.txt